version: "3.10"

services:
  frontend:
    build:
      context: .
      dockerfile: Streamlit_Frontend/Dockerfile
    image: frontend:latest
    ports:
      - 8501:8501
      - 5000:5000
    networks:
      - project_network
    depends_on:
      - backend
    volumes:
      - ./Streamlit_Frontend/Generate_Recommendations.py:/app/frontend/Generate_Recommendations.py


  backend:
    build:
      context: .
      dockerfile: FastAPI_Backend/Dockerfile
    image: backend:latest
    volumes:
      - 'C:\Users\kkton\OneDrive\Documents\Orbital\Diet-Recommendation-System\FastAPI_Backend\main.py:/app/backend/main.py'
    ports:
      - 8080:8080
    networks:
      - project_network
networks:
  project_network: